#!/usr/bin/env bash
# shellcheck shell=bash
# Displays "Best School" 10 times, with "Hi" printed after the 9th iteration

i=1
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    ((i++))
done
