#!/usr/bin/env bash
# shellcheck shell=bash
# Checks if the file 'school' exists, is a regular file, and is not empty

if [ -e school ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi

if [ -f school ]; then
    echo "school is a regular file"
fi

if [ -s school ]; then
    echo "school file is not empty"
else
    echo "school file is empty"
fi
