#!/usr/bin/env bash
# Gives information about the file "school" in the current directory.
if [ -e school ]
then
    if [ -d school ]
    then
        echo "school exists but it's a directory"
    else
        if [ -s school ]
        then
            if [ -f school ]
            then
                echo "school exists, is not empty and is a regular file"
            else
                echo "school exists and is not empty"
            fi
        else
            echo "school is empty"
        fi
    fi
else
    echo "school does not exist"
fi
