#!/usr/bin/env bash
# shellcheck shell=bash
# Displays content of current directory in list format, showing only the part after the first dash

for file in *; do
    if [[ "$file" != .* ]]; then
        echo "${file#*-}"
    fi
done
