#!/bin/bash
printf "w,s,b='water','stir.','bestchol'\nf=lambda n,a:sum(a.index(c)*len(a)**i for i,c in enumerate(n[::-1]))\nt=lambda n,a:(t(n//len(a),a)+a[n%%len(a)]) if n else ''\nprint(t(f('$WATER',w)+f('$STIR',s),b) or b[0])\n" | python3
